[env:m5stick-c]
platform = espressif32@6.1.0
board = m5stick-c
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git